---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  roles:
  - common

# Configure and deploy master worker.
- hosts: crawl-master
  roles:
  - database

