---
# This role contains common plays that will run on all nodes.

- name: Update apt packages
  become: yes
  apt: update_cache=yes

- name: Install Git
  become: yes
  apt: name=git state=present

- name: Install NVM v0.31.0
  register: nodechange
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | sh
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

- name: Install Node v4.2.6
  when: nodechange.changed
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 4.2.6 && nvm alias default 4.2.6"
    creates=/home/{{ ansible_user_id }}/.nvm/alias

- name: Install PM2
  npm: name=pm2 global=yes executable=/home/{{ ansible_user_id }}/.nvm/versions/node/v4.2.6/bin/npm state=present